// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBionqi7-WKaTW0pocgy3iBFdKYtLbGL54',
    appId: '1:691068322845:web:11722fd0c5c8c3b04df2f4',
    messagingSenderId: '691068322845',
    projectId: 'bookstore-64d33',
    authDomain: 'bookstore-64d33.firebaseapp.com',
    storageBucket: 'bookstore-64d33.appspot.com',
    measurementId: 'G-C8EYK76PYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JFzNwFHePWo-QnwQ5FD-sQYunCRqUoQ',
    appId: '1:691068322845:android:7c49ce9046cc82994df2f4',
    messagingSenderId: '691068322845',
    projectId: 'bookstore-64d33',
    storageBucket: 'bookstore-64d33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAoH975xUKRRgQtWyFc_XADYv-NaZd-zc',
    appId: '1:691068322845:ios:5e12033bfc9fa1da4df2f4',
    messagingSenderId: '691068322845',
    projectId: 'bookstore-64d33',
    storageBucket: 'bookstore-64d33.appspot.com',
    iosClientId: '691068322845-3c2uqbc0njhieab70fk7v4itus4lrge0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAoH975xUKRRgQtWyFc_XADYv-NaZd-zc',
    appId: '1:691068322845:ios:5e12033bfc9fa1da4df2f4',
    messagingSenderId: '691068322845',
    projectId: 'bookstore-64d33',
    storageBucket: 'bookstore-64d33.appspot.com',
    iosClientId: '691068322845-3c2uqbc0njhieab70fk7v4itus4lrge0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );
}
